// Copyright 2026 RegaliumOS™.
// SPDX-License-Identifier: Apache-2.0

package emit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/oh-tarnished/digital-buildings-protobuf/sync/describe"
	"github.com/oh-tarnished/digital-buildings-protobuf/sync/naming"
)

// wrapWidth keeps generated comments inside a readable column. buf format does
// not reflow comments, so this is the only thing that does.
const wrapWidth = 74

// javaRoot is the Java package prefix. Rule 3 mandates all three java_*
// options and forbids go_package: api-linter requires one and not the other.
//
// It is the reverse of a domain the publisher controls -- regalium.com -- not
// an io.github.* fallback. Sibling repositories in the-protobuf-project use
// io.github.theprotobufproject, which is the correct choice for a project
// without a domain and the wrong one for a project with it.
//
// Changing this restamps every emitted file, so it is a decision rather than a
// detail. It does not touch sync/ordinals.yaml: the ledger is keyed by proto
// package and message name, and neither moves with the Java prefix.
const javaRoot = "com.regalium"

// File accumulates one .proto.
type File struct {
	Path    string // repo-relative
	Package string
	Name    string // base name without .proto, for java_outer_classname
	imports map[string]bool
	body    strings.Builder
	banner  string
}

// newFile starts a file. Every generated file carries the DO NOT EDIT banner
// naming the ontology revision it came from, so "which ontology is this?" is
// answerable from any single .proto a consumer holds (rule 9).
func newFile(dir, name, pkg, banner string) *File {
	return &File{
		Path:    dir + "/" + name + ".proto",
		Package: pkg,
		Name:    name,
		imports: map[string]bool{},
		banner:  banner,
	}
}

func (f *File) importPath(p string) { f.imports[p] = true }

// line writes one line of body at the given indent.
func (f *File) line(indent int, format string, args ...any) {
	if format != "" {
		f.body.WriteString(strings.Repeat("  ", indent))
		fmt.Fprintf(&f.body, format, args...)
	}
	f.body.WriteByte('\n')
}

// comment writes a wrapped // comment block.
func (f *File) comment(indent int, body string) {
	pad := strings.Repeat("  ", indent)
	for _, l := range describe.Wrap(body, wrapWidth-len(pad)) {
		if l == "" {
			f.body.WriteString(pad + "//\n")
			continue
		}
		f.body.WriteString(pad + "// " + l + "\n")
	}
}

// String renders the whole file: banner, syntax, package, imports, options,
// then body. api-linter checks the option set, buf checks the ordering.
func (f *File) String() string {
	var b strings.Builder
	b.WriteString("// Copyright 2026 RegaliumOS™.\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n")
	b.WriteString("//\n")
	b.WriteString("// Generated by sync from Google's Digital Buildings ontology,\n")
	b.WriteString("// " + f.banner + ".\n")
	b.WriteString("// Portions Copyright 2020 Google LLC, licensed under Apache-2.0.\n")
	b.WriteString("// DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: just sync\n")
	b.WriteString("// Revision history: docs/spec.md\n\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString("package " + f.Package + ";\n\n")

	if len(f.imports) > 0 {
		paths := make([]string, 0, len(f.imports))
		for p := range f.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			b.WriteString("import \"" + p + "\";\n")
		}
		b.WriteByte('\n')
	}
	b.WriteString("option java_multiple_files = true;\n")
	b.WriteString("option java_outer_classname = \"" + naming.Message(f.Name) + "Proto\";\n")
	b.WriteString("option java_package = \"" + javaRoot + "." + f.Package + "\";\n\n")
	b.WriteString(strings.TrimRight(f.body.String(), "\n"))
	b.WriteByte('\n')
	return b.String()
}

// The well-known and googleapis imports, named once so a typo is a compile
// error here rather than a resolution failure in buf.
const (
	importFieldBehavior = "google/api/field_behavior.proto"
	importFieldInfo     = "google/api/field_info.proto"
	importResource      = "google/api/resource.proto"
	importAnnotations   = "google/api/annotations.proto"
	importClient        = "google/api/client.proto"
	importValidate      = "buf/validate/validate.proto"
	importEmpty         = "google/protobuf/empty.proto"
	importFieldMask     = "google/protobuf/field_mask.proto"
	importTimestamp     = "google/protobuf/timestamp.proto"
	importDescriptor    = "google/protobuf/descriptor.proto"
)
