// Copyright 2026 RegaliumOS™.
// SPDX-License-Identifier: Apache-2.0

// Package ordinals is the append-only field-number ledger. Stage 8, and the
// only stage that reads its own previous output.
//
// Rule 9: the ontology inserts new fields alphabetically into existing `uses`
// lists, so numbering by position would renumber half of a 450-field
// AirHandlingUnit on a routine bump. That is a wire break no linter sees, and
// `buf breaking` cannot see it either -- run against a regenerated tree, both
// sides are internally consistent.
package ordinals

import (
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

// Reserved is the range held for the fields on every read path: name, uid,
// code, entity_type and the connection list. Rule 9 fixes it at 1-15, which is
// also protobuf's one-byte tag range.
const Reserved = 15

// Ledger maps a message's fully qualified name to its field assignments.
type Ledger struct {
	// Messages is keyed by the proto package + message name, so two resources
	// with the same message name in different packages cannot collide.
	Messages map[string]*Message `yaml:"messages"`
	path     string
	dirty    bool
}

// Message is one message's slots.
type Message struct {
	// Fields maps a field name to its number. Never reassigned.
	Fields map[string]int `yaml:"fields"`
	// Retired holds numbers whose field the ontology no longer has. They are
	// emitted as `reserved` and never returned to circulation: a consumer may
	// still hold a message that used one.
	Retired []int `yaml:"retired,omitempty"`
	// Next is the lowest number never yet handed out.
	Next int `yaml:"next"`
}

// Load reads the ledger, creating an empty one if it does not exist.
func Load(path string) (*Ledger, error) {
	l := &Ledger{Messages: map[string]*Message{}, path: path}
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return l, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read ledger: %w", err)
	}
	if err := yaml.Unmarshal(b, l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if l.Messages == nil {
		l.Messages = map[string]*Message{}
	}
	l.path = path
	return l, nil
}

// Assign returns the number for a field, allocating one if it is new. The
// order of calls does not matter: an existing field keeps its slot whatever
// position it now occupies in the ontology.
func (l *Ledger) Assign(message, field string) int {
	m, ok := l.Messages[message]
	if !ok {
		m = &Message{Fields: map[string]int{}, Next: Reserved + 1}
		l.Messages[message] = m
		l.dirty = true
	}
	if m.Fields == nil {
		m.Fields = map[string]int{}
	}
	if n, ok := m.Fields[field]; ok {
		return n
	}
	n := m.Next
	if n <= Reserved {
		n = Reserved + 1
	}
	// 19000-19999 is reserved by protobuf itself.
	for n >= 19000 && n <= 19999 {
		n = 20000
	}
	m.Fields[field] = n
	m.Next = n + 1
	l.dirty = true
	return n
}

// Number looks a field's slot up without allocating one. The Markdown
// reference reads the ledger this way: a docs run must never assign a number,
// because the number a consumer relies on is the one `just sync` committed.
func (l *Ledger) Number(message, field string) (int, bool) {
	m, ok := l.Messages[message]
	if !ok {
		return 0, false
	}
	n, ok := m.Fields[field]
	return n, ok
}

// Retire moves the numbers of fields the ontology no longer has into the
// message's reserved range. Called once per message after every Assign, with
// the set of names still present.
func (l *Ledger) Retire(message string, present map[string]bool) {
	m, ok := l.Messages[message]
	if !ok {
		return
	}
	for name, n := range m.Fields {
		if present[name] {
			continue
		}
		delete(m.Fields, name)
		m.Retired = append(m.Retired, n)
		l.dirty = true
	}
	sort.Ints(m.Retired)
}

// Reserved returns the numbers a message must declare `reserved`.
func (l *Ledger) ReservedFor(message string) []int {
	m, ok := l.Messages[message]
	if !ok {
		return nil
	}
	return m.Retired
}

// Save writes the ledger back if anything changed.
func (l *Ledger) Save() error {
	if !l.dirty {
		return nil
	}
	b, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	header := "# Field-number ledger. Append-only; generated by `just sync`.\n" +
		"#\n" +
		"# Rule 9: field numbers come from here, never from position. The ontology\n" +
		"# adds fields to existing types alphabetically, so a generator numbering by\n" +
		"# position would renumber half of a large message on a routine spec bump --\n" +
		"# a wire break that `buf breaking` cannot see, because both sides of the\n" +
		"# comparison were regenerated the same way.\n" +
		"#\n" +
		"# Never edit a number by hand. A retired number is never reissued: a\n" +
		"# consumer may still hold a message that used it.\n" +
		"#\n" +
		"# .gitattributes marks this file -merge, so git cannot resolve a conflict\n" +
		"# here by guessing. A conflict means two branches each assigned a slot,\n" +
		"# which is a compatibility decision a merge algorithm must not make.\n"
	return os.WriteFile(l.path, append([]byte(header), b...), 0o644)
}

// Dirty reports whether Save would write, which `just verify-schema` uses to
// fail when regenerating would move a slot.
func (l *Ledger) Dirty() bool { return l.dirty }
