// Copyright 2026 RegaliumOS™.
// SPDX-License-Identifier: Apache-2.0

// Package docs renders the Markdown reference that sits beside the schema.
// Stage 9, and sync/emit's sibling rather than its consumer.
//
// Rule 2: nothing under protobuf/ is written by hand, and that covers the
// README.md files as much as the .proto files. Both targets are built from the
// same model.Model, and this one does **not** parse the emitted protos back
// in. A reference generated by re-reading the output would agree with the
// output by construction and so could not catch a generator that emitted the
// wrong thing; built from the model, the two agree only when both are right.
//
// What that costs is a rule: anything both targets have to know is a model
// decision, not an emitter detail. Field types and field behaviours moved to
// model.Field for exactly this reason -- see sync/model/field.go.
package docs

import (
	"path"
	"sort"
	"strings"

	"github.com/oh-tarnished/digital-buildings-protobuf/sync/model"
	"github.com/oh-tarnished/digital-buildings-protobuf/sync/ontology"
	"github.com/oh-tarnished/digital-buildings-protobuf/sync/ordinals"
)

// Page is one Markdown file: a path relative to the repository root, and its
// whole content.
type Page struct {
	Path    string
	Content string
}

// Renderer holds what every page needs: the ontology, for the prose the
// ontology already carries, and the banner naming the pinned revision.
type Renderer struct {
	onto   *ontology.Ontology
	ledger *ordinals.Ledger
	banner string
}

// New starts a renderer. The ledger is read but never written: a docs run must
// not assign a field number, because the number a consumer relies on is the one
// `just sync` committed. It may be nil, in which case the reference omits the
// numbers rather than inventing them.
func New(o *ontology.Ontology, l *ordinals.Ledger, banner string) *Renderer {
	return &Renderer{onto: o, ledger: l, banner: banner}
}

// number is a field's committed wire slot, or "--" if the ledger has not seen
// it -- which means `just sync` has not run since the field appeared.
func (r *Renderer) number(res *model.Resource, f model.Field) string {
	if r.ledger == nil {
		return "--"
	}
	if n, ok := r.ledger.Number(res.Package+"."+res.Message, f.Name); ok {
		return itoa(n)
	}
	return "--"
}

// Render builds every page: one README.md per package, plus the index that
// lists them. The order is deterministic so a regenerate-and-diff run is
// meaningful.
func (r *Renderer) Render(m *model.Model) []Page {
	resources := append([]*model.Resource(nil), m.Resources...)
	sort.Slice(resources, func(i, j int) bool {
		if resources[i].Namespace != resources[j].Namespace {
			return resources[i].Namespace < resources[j].Namespace
		}
		return resources[i].Segment < resources[j].Segment
	})

	pages := []Page{r.index(m, resources)}
	for _, res := range resources {
		pages = append(pages, Page{
			Path:    path.Join(res.Dir, "README.md"),
			Content: r.resource(res),
		})
	}
	return pages
}

// doc is a Markdown builder. It exists so a page reads as a sequence of
// blocks rather than as string concatenation, and so every block is separated
// by exactly one blank line without anyone having to remember.
type doc struct {
	b      strings.Builder
	blocks int
}

func (d *doc) block(s string) {
	if s == "" {
		return
	}
	if d.blocks > 0 {
		d.b.WriteString("\n")
	}
	d.b.WriteString(s)
	d.b.WriteString("\n")
	d.blocks++
}

func (d *doc) line(s string)                        { d.block(s) }
func (d *doc) heading(level int, s string)          { d.block(strings.Repeat("#", level) + " " + s) }
func (d *doc) String() string                       { return d.b.String() }
func (d *doc) table(head []string, rows [][]string) { d.block(table(head, rows)) }

// banner is the DO NOT EDIT header. It is an HTML comment rather than a
// heading so it does not render, and it names the revision for the same
// reason every .proto does: "which ontology is this from?" has to be
// answerable from any single file a consumer holds (rule 9).
func (r *Renderer) bannerBlock() string {
	return "<!--\nGenerated by `just docs` from Google's Digital Buildings ontology,\n" +
		r.banner + ".\nDO NOT EDIT -- edit sync/internal/docs and regenerate.\n-->"
}
